# This is a basic workflow to help you get started with Actions

name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test
        run:  for f in ${{ matrix.product }}/t/*.sh ; do $f && continue; echo FAIL $f; exit 1; done
        env:
          ENVIRON_TEST_IMAGE: opensuse/leap
